<!-- search -->
<?php include_once VIEWS . "core/" . TEMPLATE . '/metro/search.phtml'; ?>

<!-- settings -->
<?php include_once VIEWS . "core/" . TEMPLATE . '/metro/settings.phtml'; ?>

<!--SEM IMAGEM-->
<!--<div class="tile-area tile-area-scheme-darkCobalt fg-white">-->

<!--COM IMAGEM-->
<div class="fg-white">

    <!-- user-bar -->
    <?php include_once VIEWS . "core/" . TEMPLATE . '/metro/user-bar.phtml'; ?>

    <!-- content -->
    <?php echo $tView_content; ?>

</div>