<script type="text/javascript">
    $(function () {
        $('#fCadastro').populate(<?php echo $view_json_objeto; ?>);
    });
</script>
<ul class="breadcrumbs">
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Principal'); ?>"><span class="icon mif-home"></span></a></li>
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Gestao'); ?>">Gestão</a></li>
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Pessoa'); ?>">Pessoas</a></li>
    <li><a>Edição</a></li>
</ul>

<h1 class="text-light">
    Pessoa/Cliente <small class="on-right"> Editar</small>
    <span class="mif-user-plus place-right"></span>
</h1>

<hr class="thin bg-grayLighter">
<br>

<form id="fCadastro" action="<?php echo UrlRequestHelper::mountUrlPost('Pessoa', 'atualizar'); ?>" method="POST" data-role="validator">
    <input type="hidden" name="id" id="id" >
    <div class="flex-grid">
        <div class="row cell-auto-size cells12">
            <div class="cell colspan8">
                <label>Nome <b class="fg-red">*</b></label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           id="nome"
                           name="nome"
                           placeholder="Informe o nome completo sem abreveações" 
                           maxlength="100"
                           data-validate-func="minlength" 
                           data-validate-arg="4"
                           data-validate-hint="Minimo de 4 caracteres"
                           data-validate-hint-position="top"
                           autocomplete="off"
                           >
                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
            <div class="cell colspan4 padding-inputs-left1">
                <label>Apelido</label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           name="apelido"
                           placeholder="Informe um apelido" 
                           maxlength="100"
                           autocomplete="off"
                           >
                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
        </div>

        <div class="row cell-auto-size cells3">
            <div class="cell colspan3">
                <label>Número CPF <b class="fg-red">*</b></label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           id="numeroCPF"
                           name="numeroCPF"
                           disabled="disabled"
                           >

                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
            <div class="cell colspan3 padding-inputs-left1">
                <label>Data de Nascimento <b class="fg-red">*</b></label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text"
                           id="dataNascimento"
                           name="dataNascimento"
                           data-validate-func="required"
                           data-validate-hint-position="top"
                           data-validate-hint="Informe uma data de nascimento válida"
                           placeholder="Informe uma data de Nascimento" 
                           maxlength="15"
                           autocomplete="off"
                           >

                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
            <div class="cell padding-inputs-left1">
                <label>Email <b class="fg-red">*</b></label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           id="email"
                           name="email"
                           placeholder="Informe o email pessoal" 
                           maxlength="115"
                           autocomplete="off"
                           >

                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
        </div>

        <div class="row cell-auto-size">
            <div class="cell colspan12">
                <label>Observações</label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           name="observacao"
                           placeholder="Observações adicionais" 
                           maxlength="100"
                           autocomplete="off"
                           >

                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
        </div>        
        <div class="row">
            <div class="cell colspan12">
                <h3 class="fg-gray">Informações de Domicílio</h3>
            </div>
        </div>
        <hr class="thin bg-grayLighter"/>
        <div class="row cell-auto-size">
            <div class="cell colspan7">
                <label>Endereço</label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           name="endereco"
                           placeholder="Informe o logradouro" 
                           maxlength="100"
                           autocomplete="off"
                           >
                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
            <div class="cell colspan1">
                <label>Número</label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           name="numeroEndereco"
                           maxlength="100"
                           autocomplete="off"
                           >
                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
            <div class="cell colspan4 padding-inputs-left1">
                <label>Complemento</label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           name="complemento"
                           placeholder="Complementos Adicionais ao Endereço" 
                           maxlength="100"
                           autocomplete="off"
                           >
                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
        </div>
        <div class="row cell-auto-size">
            <div class="cell colspan5">
                <label>Bairro</label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           name="bairro"
                           placeholder="Bairro de residência" 
                           maxlength="100"
                           autocomplete="off"
                           >
                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
            <div class="cell colspan2 padding-inputs-left1">
                <label>Estado</label>
                <div class="input-control full-size" data-role="select" data-placeholder="Selecione...">
                    <select name="estado"
                            id="estado"
                            data-validate-func="required"
                            data-validate-hint-position="top"
                            data-validate-hint="Por Favor, preencha esse campo.">
                        <option></option>
                        <?php foreach ($view_listEstado as $objEstado): ?>
                            <option value="<?php echo $objEstado->getId(); ?>"><?php echo $objEstado->getNome(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="cell colspan3">
                <label>Cidade</label>
                <div class="input-control full-size" data-role="select" data-placeholder="Selecione um Orgao Pagador">
                    <select name="cidade"
                            id="cidade"
                            data-validate-func="required"
                            data-validate-hint-position="top"
                            data-validate-hint="Por Favor, preencha esse campo.">
                        <option value=""></option>
                        <?php foreach ($view_listCidade as $objCidade): ?>
                            <option value="<?php echo $objCidade->getId(); ?>"><?php echo $objCidade->getNome(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="cell colspan2 padding-inputs-left1">
                <label>CEP</label>
                <div class="input-control text full-size" data-role="input">
                    <input type="text" 
                           name="numeroCEP"
                           id="numeroCEP"
                           placeholder="Número do CEP" 
                           maxlength="100"
                           autocomplete="off"
                           >
                    <button class="button helper-button clear"><span class="mif-cross"></span></button>
                    <span class="input-state-error mif-warning"></span>
                    <span class="input-state-success mif-checkmark"></span>
                </div>
            </div>
        </div>
        <br/>
        <div class="row flex-just-end">
            <div class="cell">
                <button class="button mif-floppy-disk primary">&nbsp;Salvar</button>
            </div>
        </div>
        <br/>
        <div class="row cell-auto-size cells12">
            <div class="cell colspan12">
                <div data-text="logs" class="example">
                    <?php echo $view_logCriacao; echo $view_logAtualizacao; ?>
                </div>
            </div>
        </div>
    </div>

</form>