<ul class="breadcrumbs">
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Principal'); ?>"><span class="icon mif-home"></span></a></li>
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Gestao'); ?>">Gestão</a></li>
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Consulta'); ?>">Consultas</a></li>
</ul>

<h1 class="text-light">
    Consulta de Clientes <small class="on-right"></small>
    <span class="mif-search place-right"></span>
</h1>

<hr class="thin bg-grayLighter">

<div class="toolbar">
    <div class="toolbar-section">
        <button data-role="hint" data-hint="Novo|Clique para cadastrar uma nova colsulta" 
                onclick="redirectUrl('<?php echo UrlRequestHelper::mountUrl('PessoaConsulta', 'cadastrar'); ?>')" 
                class="toolbar-button"><span class="mif-plus"></span></button>
    </div>
</div>
<br />
<div class="row cell-auto-size">
    <div class="cell">
        <table class="dataTable border bordered hovered no-footer" id="listConsultas" style="width: 100%">
            <thead>
                <tr>
                    <td class="sortable-column">Nome</td>
                    <td class="sortable-column">Número CPF</td>
                    <td class="sortable-column">Orgão</td>
                    <td class="sortable-column">Margem Disponível</td>
                    <td class="sortable-column">Data da Consulta</td>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

