<ul class="breadcrumbs">
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Principal'); ?>"><span class="icon mif-home"></span></a></li>
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Gestao'); ?>">Gestão</a></li>
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Consulta'); ?>">Consultas</a></li>
    <li><a>Cadastro</a></li>
</ul>
<h1 class="text-light">
    Consultas <small class="on-right"> Selecionar</small>
    <span class="mif-search place-right"></span>
</h1>
<hr class="thin bg-grayLighter">
<div class="flex-grid">
    <div class="row cell-auto-size no-margin">
        <div class="cell colspan6">
            <label>Nome</label>
            <div class="input-control text full-size" data-role="input">
                <span class="mif-user prepend-icon"></span>
                <input type="text" 
                       value="<?php echo $view_objPessoa->getNome(); ?>"
                       disabled="disabled"                     
                       >
            </div>
        </div>
        <div class="cell colspan3">
            <label>Data de Nascimento</label>
            <div class="input-control text full-size" data-role="input">
                <span class="mif-calendar prepend-icon"></span>
                <input type="text" 
                       value="<?php echo $view_objPessoa->getDataNascimento(); ?>"
                       disabled="disabled"
                       data-role='hint' 
                       data-hint-background='bg-lightBlue' 
                       data-hint-color='fg-white'
                       data-hint-mode='2'
                       data-hint='|<?php echo DataHelper::calcularIdade($view_objPessoa->getDataNascimento()); ?> anos' 
                       data-hint-position='bottom'
                       >
            </div>
        </div>
        <div class="cell colspan3">
            <label>Número CPF</label>
            <div class="input-control text full-size" data-role="input">
                <span class="mif-credit-card prepend-icon"></span>
                <input type="text" 
                       value="<?php echo $view_objPessoa->getNumeroCPF(); ?>"
                       disabled="disabled"
                       >
            </div>
        </div>
    </div>
    <div class="row cell-auto-size toolbar_title no-margin">
        <div class="cell colspan10">
            <h3 class="fg-gray">Orgãos Associados</h3>
        </div>
    </div>
    <hr class="thin bg-grayLighter" style="margin-top: -5px;"/>
    <div class="row cell-auto-size">
        <div class="cell colspan12">
            <?php if($view_isOrgao): ?>
            <table id="main_table_demo" class="dataTable border bordered hovered no-footer">
                <thead>
                    <tr>
                        <th>Orgão Pagador</th>
                        <th>Situação</th>
                        <th>Matricula</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($view_listPessoaOrgao as $objPessoaOrgao): ?>
                        <tr>
                            <td><?php echo $objPessoaOrgao->getOrgao()->getNome(); ?></td>
                            <td><?php echo $objPessoaOrgao->getTipoSituacao()->getNome(); ?></td>
                            <td><?php echo $objPessoaOrgao->getMatricula(); ?></td>
                            <td><button onclick="redirectUrl('<?php echo UrlRequestHelper::mountUrl('PessoaConsulta', 'cadastrar', array('id' => $view_objPessoa->getId(),'idOrgao'=>$objPessoaOrgao->getId())); ?>')" 
                                        class="button small-button place-right" 
                                        style="margin-bottom: -5px; margin-top: -5px;">
                                    <span class="mif-checkmark fg-emerald"></span> Selecionar
                                </button>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
                <span class="tag warning">Não existem orgãos associados ao cliente ou todos possuem consultas ativas</span>
            <?php endif; ?>
        </div>
    </div>
</div>
