<ul class="breadcrumbs">
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Principal'); ?>"><span class="icon mif-home"></span></a></li>
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Gestao'); ?>">Gestão</a></li>
</ul>
<div class="tile-container">
    <a href="#bussola" class="tile-small bg-grayLighter fg-gray" data-role="tile">
        <div class="tile-content iconic" data-role="hint" data-hint-background="bg-gray" data-hint-color="fg-white" data-hint-mode="2" data-hint="Bússola|Clientes Para Revenda" data-hint-position="top">
            <span class="icon mif-compass2"></span>
            <span class="tile-badge fg-gray"><?php echo $view_totalEmprestimosDisponiveis; ?></span>
        </div>
    </a>
    <a href="#aniversario" class="tile-small bg-grayLighter fg-gray" data-role="tile">
        <div class="tile-content iconic" data-role="hint" data-hint-background="bg-gray" data-hint-color="fg-white" data-hint-mode="2" data-hint="Aniversários|Aniversariantes do Mês" data-hint-position="top">
            <span class="icon mif-gift"></span>
            <span class="tile-badge fg-gray"><?php echo $view_totalAniversario; ?></span>
        </div>        
    </a>    
    <a href="#margem" class="tile-small bg-grayLighter fg-gray" data-role="tile">
        <div class="tile-content iconic" data-role="hint" data-hint-background="bg-gray" data-hint-color="fg-white" data-hint-mode="2" data-hint="Margens Disponíveis|Clientes com margem disponível para empréstimo superior a R$ 25,00" data-hint-position="top">
            <span class="icon mif-medium"></span>
            <span class="tile-badge fg-gray"><?php echo $view_totalMargensDisponiveis; ?></span>
        </div>        
    </a>
</div>
<h1 class="text-light">
    Gestão <small class="on-right"> <?php echo date("F, Y"); ?></small>
    <span class="mif-apps place-right"></span>
</h1>
<hr class="thin bg-grayLighter">

<!--<div class="toolbar">
    <div class="toolbar-section">
        <button data-role="hint" data-hint="Novo|Clique para cadastrar uma novo tipo de orgao" 
                onclick="redirectUrl('<?php //echo UrlRequestHelper::mountUrl('TipoOrgao', 'cadastrar');     ?>')" 
                class="toolbar-button"><span class="mif-plus"></span></button>
    </div>
</div>-->
<br/>
<!-- PAINEIS -->
<div class="flex-grid">
    <div class="row cell-auto-size cells12">
        <div class="cell colspan3">
            <div class="panel">
                <div class="heading bg-emerald">
                    <span class="icon mif-organization bg-darkEmerald"></span>
                    <span class="title">Clientes</span>
                    <span class='tag warning mif-ani-horizontal place-right'>CONSULTA</span>
                    <span class='tag alert mif-ani-horizontal place-right'>ORGÃO</span>
                </div>
                <div class="content padding5" style="margin-top: -10px;">
                    <div class="grid">
                        <div class="row">
                            <div class="cell align-center"><strong>Hoje</strong></div>
                            <div class="cell align-center no-tablet"><strong>Mês</strong></div>
                            <div class="cell align-center no-tablet"><strong>Ano</strong></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_tPessoaCadastradasHoje; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_tPessoaCadastradasMes; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_tPessoaCadastradasAno; ?></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_indicadorPessoaDIA; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_indicadorPessoaMES; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_indicadorPessoaANO; ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cell colspan3 padding-inputs-left1">
            <div class="panel">
                <div class="heading bg-amber">
                    <span class="icon mif-cabinet bg-orange"></span>
                    <span class="title">Contratos</span>
                    <span class='tag warning mif-ani-horizontal place-right'>FÍSICO</span>
                </div>
                <div class="content padding5" style="margin-top: -10px;">
                    <div class="grid">
                        <div class="row">
                            <div class="cell align-center"><strong>Hoje</strong></div>
                            <div class="cell align-center no-tablet"><strong>Mês</strong></div>
                            <div class="cell align-center no-tablet"><strong>Ano</strong></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_tContratoCadastradosHoje; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_tContratoCadastradosMes; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_tContratoCadastradosAno; ?></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_indicadorContratoDIA; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_indicadorContratoMES; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_indicadorContratoANO; ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cell colspan3 padding-inputs-left1">
            <div class="panel">
                <div class="heading bg-indigo">
                    <span class="icon mif-search bg-darkIndigo"></span>
                    <span class="title">Consultas</span>
                    <?php echo $view_alertConsulta; ?>
                </div>
                <div class="content padding5" style="margin-top: -10px;">
                    <div class="grid">
                        <div class="row">
                            <div class="cell align-center"><strong>Hoje</strong></div>
                            <div class="cell align-center no-tablet"><strong>Mês</strong></div>
                            <div class="cell align-center no-tablet"><strong>Ano</strong></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_tConsultaCadastradasHoje; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_tConsultaCadastradasMes; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_tConsultaCadastradasAno; ?></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_indicadorConsultaDIA; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_indicadorConsultaMES; ?></div>
                            <div class="cell align-center no-tablet"><?php echo $view_indicadorConsultaANO; ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cell colspan3 padding-inputs-left1">
            <div class="panel">
                <div class="heading">
                    <span class="icon mif-dollar2"></span>
                    <span class="title">Faturamento</span>
                </div>
                <div class="content padding5" style="margin-top: -10px;">
                    <div class="grid">
                        <div class="row">
                            <div class="cell align-center"><strong>Mês</strong></div>
                            <div class="cell align-center no-tablet"><strong>Meta</strong></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><span class="mif-money fg-dark"><?php echo $view_faturamentoMES; ?></span></div>
                            <div class="cell align-center no-tablet"><span class="mif-money fg-dark">--</span></div>
                        </div>   
                        <div class="row" style="margin-bottom: -10px;">
                            <div class="progress small" data-value="15" data-color="ribbed-amber" data-role="progress"></div>
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <div class="row cell-auto-size cells12">
        <div class="cell colspan3">
            <div class="panel">
                <div class="heading bg-cobalt">
                    <span class="icon mif-mail-read bg-darkCobalt"></span>
                    <span class="title">Marketing</span>
                </div>
                <div class="content padding5" style="margin-top: -10px;">
                    <div class="grid">
                        <div class="row">
                            <div class="cell align-center"><strong>Hoje</strong></div>
                            <div class="cell align-center no-tablet"><strong>Mês</strong></div>
                            <div class="cell align-center no-tablet"><strong>Ano</strong></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center">--<?php //echo $view_tContratoCadastradosHoje;   ?></div>
                            <div class="cell align-center no-tablet">--<?php //echo $view_tContratoCadastradosMes;   ?></div>
                            <div class="cell align-center no-tablet">--<?php //echo $view_tContratoCadastradosAno;   ?></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center">--<?php //echo $view_indicadorContratoDIA;   ?></div>
                            <div class="cell align-center no-tablet">--<?php //echo $view_indicadorContratoMES;   ?></div>
                            <div class="cell align-center no-tablet">--<?php //echo $view_indicadorContratoANO;   ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cell colspan3 padding-inputs-left1">
            <div class="panel">
                <div class="heading bg-red">
                    <span class="icon mif-phone bg-darkRed"></span>
                    <span class="title">Telemarketing</span>
                    <span class='tag warning mif-ani-horizontal place-right'>AGENDA</span>
                </div>
                <div class="content padding5" style="margin-top: -10px;">
                    <div class="grid">
                        <div class="row">
                            <div class="cell align-center"><strong>Hoje</strong></div>
                            <div class="cell align-center no-tablet"><strong>Mês</strong></div>
                            <div class="cell align-center no-tablet"><strong>Ano</strong></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center">--<?php //echo $view_tContratoCadastradosHoje;   ?></div>
                            <div class="cell align-center no-tablet">--<?php //echo $view_tContratoCadastradosMes;   ?></div>
                            <div class="cell align-center no-tablet">--<?php //echo $view_tContratoCadastradosAno;   ?></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center">--<?php //echo $view_indicadorContratoDIA;   ?></div>
                            <div class="cell align-center no-tablet">--<?php //echo $view_indicadorContratoMES;   ?></div>
                            <div class="cell align-center no-tablet">--<?php //echo $view_indicadorContratoANO;   ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="cell colspan3 padding-inputs-left1">
            <div class="panel">
                <div class="heading bg-teal">
                    <span class="icon mif-search bg-darkTeal"></span>
                    <span class="title">Negocial</span></span>
                </div>
                <div class="content padding5" style="margin-top: -10px;">
                    <div class="grid">
                        <div class="row">
                            <div class="cell align-center"><strong>Novo</strong></div>
                            <div class="cell align-center no-tablet no-phone"><strong>Refin.</strong></div>
                            <div class="cell align-center no-tablet no-phone"><strong>Portab.</strong></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_tNovoMES; ?></div>
                            <div class="cell align-center no-tablet no-phone"><?php echo $view_tRefinMES; ?></div>
                            <div class="cell align-center no-tablet no-phone"><?php echo $view_tPortaMES; ?></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_displayNovo; ?></div>
                            <div class="cell align-center no-tablet no-phone"><?php echo $view_displayRefin; ?></div>
                            <div class="cell align-center no-tablet no-phone"><?php echo $view_displayPorta; ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cell colspan3 padding-inputs-left1">
            <div class="panel">
                <div class="heading bg-teal">
                    <span class="icon mif-dollar bg-darkTeal"></span>
                    <span class="title">Comissão</span>
                    <span class='tag warning mif-ani-horizontal place-right'>ATRASO</span>
                </div>
                <div class="content padding5" style="margin-top: -10px;">
                    <div class="grid">
                        <div class="row">
                            <div class="cell align-center"><strong>Prevista</strong></div>
                            <div class="cell align-center"><strong>Confirmada</strong></div>
                        </div>
                        <div class="row">
                            <div class="cell align-center"><span class="mif-money fg-dark"><?php echo $view_comissaoPrevistaMES; ?></span></div>
                            <div class="cell align-center"><span class="mif-money fg-dark"><?php echo $view_comissaoConfirmadaMES; ?></span></div>
                        </div>   
                        <div class="row">
                            <div class="cell align-center"><?php echo $view_totalComissaoPrevistaMES; ?></div>
                            <div class="cell align-center"><?php echo $view_indicadorComissaoMES; ?></div>
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br/>
<div class="row cell-auto-size cells12">
    <div class="cell colspan6">
        <div class="padding10 bg-grayLighter"><span class="mif-home" style="margin-top: -7px;"></span> <strong>Principal Parceiro: </strong>Bevicred Filial Salvador<span class="place-right">R$ 1.000,99</span></div>
    </div>
    <div class="cell colspan6 padding-inputs-left1">
        <div class="padding10 bg-grayLighter"><span class="mif-suitcase" style="margin-top: -7px;"></span> <strong>Principal Corretor: </strong>Nenhum contrato teve origem de corretores<span class="place-right"></span></div>
    </div>
</div>
<br/>
<a name="bussola"></a>
<h2 class="text-light">
    Bússola <small class="on-right">Clientes para revenda</small>
    <span class="mif-compass2 place-right"></span>
</h2>
<hr class="thin bg-grayLighter">
<div class="row cell-auto-size">
    <div class="cell">
        <table class="dataTable border bordered no-footer" id="listEmprestimosDisponiveis" style="width: 100%">
            <thead>
                <tr>
                    <td class="sortable-column">Nome</td>
                    <td class="sortable-column">Número CPF</td>
                    <td class="sortable-column">Empréstimos</td>
                    <td class="sortable-column">Valor R$</td>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<br/>
<a name="aniversario"></a>
<h2 class="text-light">
    Aniversariantes <small class="on-right">do mês</small>
    <span class="mif-gift place-right"></span>
</h2>
<hr class="thin bg-grayLighter">
<div class="row cell-auto-size">
    <div class="cell">
        <table class="dataTable border bordered no-footer" id="listAniversario" style="width: 100%">
            <thead>
                <tr>
                    <td class="sortable-column">Nome</td>
                    <td class="sortable-column">Data</td>
                    <td class="sortable-column">Idade</td>
                    <td class="sortable-column">Contatos</td>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<br/>
<a name="margem"></a>
<h2 class="text-light">
    Margens <small class="on-right">Disponíveis</small>
    <span class="mif-medium place-right"></span>
</h2>
<hr class="thin bg-grayLighter">
<div class="row cell-auto-size">
    <div class="cell">
        <table class="dataTable border bordered no-footer" id="listMargensDisponiveis" style="width: 100%">
            <thead>
                <tr>
                    <td class="sortable-column">Nome</td>
                    <td class="sortable-column">Orgão</td>
                    <td class="sortable-column">Matricula</td>
                    <td class="sortable-column">Competência</td>
                    <td class="sortable-column">Consulta</td>
                    <td class="sortable-column">Margem Disponível</td>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>