<div class="charm right-side padding20 bg-grayDark" id="charmSearch">
    <button class="square-button bg-transparent fg-white no-border place-right small-button" onclick="showSearch()"><span class="mif-cross"></span></button>
    <h1 class="text-light">Pesquisa</h1>
    <hr class="thin"/>
    <br />
    <div class="input-control text full-size">
        <label>
            <span class="dropdown-toggle drop-marker-light">Anywhere</span>
            <ul class="d-menu" data-role="dropdown">
                <li><a onclick="setSearchPlace(this)">Anywhere</a></li>
                <li><a onclick="setSearchPlace(this)">Options</a></li>
                <li><a onclick="setSearchPlace(this)">Files</a></li>
                <li><a onclick="setSearchPlace(this)">Internet</a></li>
            </ul>
        </label>
        <input type="text">
        <button class="button"><span class="mif-search"></span></button>
    </div>
</div>