<!--LAYOU C/ IMAGEM-->
<div style="margin-left: 6em; margin-top: 3em;">
    <img width="250px" height="60px" src="<?php echo PATH_IMAGE_URL; ?>logo.png"> 
</div>

<!--LAYOUT S/ IMAGEM-->
<!--<h1 class="tile-area-title">
<?php //echo SIGLA_SIS; ?>
</h1>-->

<div class="tile-area-controls">
    <button data-role="hint" data-hint-position="botton" data-hint-mode="2" data-hint-background='bg-gray' data-hint-color='fg-white' data-hint="Perfil|Clique para alterar seu perfil" class="image-button icon-right bg-transparent fg-lubri bg-hover-grayLighter no-border"><span class="sub-header no-margin text-light"><?php echo $tView_nomeUsuario; ?></span> <span class="icon mif-user"></span></button>
    <!--<button class="square-button bg-transparent fg-white bg-hover-dark no-border" onclick="showSearch()"><span class="mif-search"></span></button>-->
    <!--<button class="square-button bg-transparent fg-lubri bg-hover-grayLighter no-border" onclick="showSettings()"><span class="mif-cog"></span></button>-->
    
    <!-- Alterar Senha -->
    <button data-role="hint" data-hint-position="botton" data-hint-mode="2" data-hint-background='bg-orange' data-hint-color='fg-white' data-hint="Alterar Senha|Clique para alterar a senha" 
            onclick="redirectUrl('<?php echo UrlRequestHelper::mountUrl('Security', 'alterarSenha'); ?>')"
            class="button square-button bg-orange fg-white bg-hover-darkOrange no-border"><span class="mif-key"></span></button>

    <!-- Deslogar -->
    <button data-role="hint" data-hint-position="botton" data-hint-mode="2" data-hint-background='bg-red' data-hint-color='fg-white' data-hint="Deslogar|Clique para para sair do sistema" 
            onclick="redirectUrl('<?php echo UrlRequestHelper::mountUrlGet('Security', 'deslogar'); ?>')"
            class="button square-button bg-red fg-white bg-hover-darkRed no-border"><span class="mif-switch"></span></button>
</div>