<ul class="breadcrumbs">
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Principal'); ?>"><span class="icon mif-home"></span></a></li>
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Gestao'); ?>">Gestão</a></li>
    <li><a>Pessoas/Clientes</a></li>
</ul>

<h1 class="text-light">
    Pessoas/Clientes <small class="on-right"> Listar</small>
    <span class="mif-organization place-right"></span>
</h1>

<hr class="thin bg-grayLighter">

<div class="toolbar">
    <div class="toolbar-section">
        <button data-role="hint" 
                data-hint="Novo|Clique para cadastrar uma novo tipo de orgao" 
                onclick="redirectUrl('<?php echo UrlRequestHelper::mountUrl('Pessoa', 'cadastrar',array('simples' => false)); ?>')" 
                class="toolbar-button">
            <span class="mif-plus"></span>
        </button>
        <button data-role="hint" 
                data-hint="Simplificado|Clique para cadastrar uma nova pessoa no modo rápido" 
                onclick="redirectUrl('<?php echo UrlRequestHelper::mountUrl('Pessoa', 'cadastrar',array('simples' => true)); ?>')" 
                class="toolbar-button">
            <span class="mif-fire"></span>
        </button>
    </div>
</div>
<br />
<div class="row cell-auto-size">
    <div class="cell">
        <table class="dataTable border bordered no-footer" id="listPessoas" style="width: 100%">
            <thead>
                <tr>
                    <td class="sortable-column">Nome</td>
                    <td class="sortable-column">Número CPF</td>
                    <td class="sortable-column">Data de Nascimento</td>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
