<div class="flex-grid">
    <div class="row">
        <div class="cell colspan4"></div>
        <div class="cell colspan8">
            <h1 class="fg-grayLight" style="font-size: 100px;">
                <?php echo $view_erro; ?>
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="cell colspan4"></div>
        <div class="cell colspan8 padding10">
            <span class="fg-gray"><?php echo $view_message; ?></span>
        </div>
    </div>
</div>