<div class="app-bar fixed-top darcula" data-role="appbar">
    <a href="<?php echo UrlRequestHelper::mountUrl('Principal'); ?>" class="app-bar-element branding">
        <?php // echo SIGLA_SIS; ?>
        <div class="align-center">
            <img  src="<?php echo PATH_IMAGE_URL; ?>logo_branca.png"> 
        </div>
    </a>
    <span class="app-bar-divider"></span>

    <div class="app-bar-element place-right">
        <span class="mif-cog"></span>
    </div>
</div>
