<ul class="breadcrumbs">
    <li><a href="<?php echo UrlRequestHelper::mountUrl('Principal'); ?>"><span class="icon mif-home"></span></a></li>
    <li><a>Institucional</a></li>
</ul>

<h1 class="text-light">Institucional <span class="mif-apps place-right"></span></h1>
<hr class="thin bg-grayLighter">


<a href="<?php echo UrlRequestHelper::mountUrl('Usuario'); ?>" class="tile bg-cyan fg-white" data-role="tile">
    <div class="tile-content iconic">
        <span class="icon mif-organization"></span>
    </div>
    <span class="tile-label">Usuários</span>
</a>